files: ^ebilling_postfinance/

repos:

# black
- repo: https://github.com/ambv/black
  rev: 18.9b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: debug-statements
    language_version: python3

# flake8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    name: flake8 except __init__.py
    exclude: __init__.py
    language_version: python3
  - id: flake8
    name: flake8 only __init__.py
    args: [--ignore=F401]  # ignore imported unused in __init__.py
    files: __init__.py
    language_version: python3

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    language_version: python3

# isort
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    language_version: python3
